<<<<<<< HEAD
"use client";

import React from "react";
import { CommunityProvider } from "src/context/CommunityContext";
=======
export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}
>>>>>>> f7c82eaeab60ec2a9faa7b220126f2f5045f3151

export default function RootLayout({
  children,
}: {
<<<<<<< HEAD
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <CommunityProvider>{children}</CommunityProvider>
      </body>
    </html>
  );
=======
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  )
>>>>>>> f7c82eaeab60ec2a9faa7b220126f2f5045f3151
}
