// src/app/layout.tsx
import React from "react";
import LayoutClient from "./layout-client"; // Import the client component

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

interface RootLayoutProps {
  children: React.ReactNode;
}

const RootLayout: React.FC<RootLayoutProps> = ({ children }) => {
  return (
    <html lang="en">
      <body>
        <LayoutClient>{children}</LayoutClient>
      </body>
    </html>
  );
};

export default RootLayout;
